### PR TITLE
Create test_20211004_06

### PR DESCRIPTION
**Pull request by Test3hara**
Test3_Comment

### CODE REVIEW

**Comment by Test1hara** [comment]
Test1_Comment

**Comment by Test3hara** [comment]
Test3_Comment

**Comment by Test2hara** [comment]
Test2_Comment

**Comment by Test3hara** [comment]
Test3_Close

**Comment by Test3hara** [comment]
Test3_Reopen

**Comment by Test2hara** [comment]
Test2_Close

**Comment by Test2hara** [comment]
Test2_Reopen

**Pull request merged**
